using System;
using System.Collections.Generic;
using Xunit;

namespace LeetcodeChallenges.Test
{
    public class Solution_00003_LengthOfLongestSubstringTest
    {
        Solution_00003_LengthOfLongestSubstring obj = new Solution_00003_LengthOfLongestSubstring();
        [Fact]
        public void case_1()
        {
            var result = obj.LengthOfLongestSubstring("a");
            Assert.Equal(1, result);
        }

        [Fact]
        public void case_2()
        {
            var result = obj.LengthOfLongestSubstring("bbbbbbb");
            Assert.Equal(1, result);
        }

        [Fact]
        public void case_3()
        {
            var result = obj.LengthOfLongestSubstring("abcdefghijklmn");
            Assert.Equal(14, result);
        }

        [Fact]
        public void case_4()
        {
            var result = obj.LengthOfLongestSubstring("abcdefghijklmna");
            Assert.Equal(14, result);
        }

        [Fact]
        public void case_5()
        {
            var result = obj.LengthOfLongestSubstring("");
            Assert.Equal(0, result);
        }

        [Fact]
        public void case_6()
        {
            var result = obj.LengthOfLongestSubstring("bbbbb");
            Assert.Equal(1, result);
        }

        [Fact]
        public void case_7()
        {
            var result = obj.LengthOfLongestSubstring("abcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmnaabcdefghijklmna");
            Assert.Equal(14, result);
        }

        [Fact]
        public void case_8()
        {
            var result = obj.LengthOfLongestSubstring("abcdefghijklmnabcaaa");
            Assert.Equal(14, result);
        }

        [Fact]
        public void case_9()
        {
            var result = obj.LengthOfLongestSubstring("cdd");
            Assert.Equal(2, result);
        }
        [Fact]
        public void case_10()
        {
            var result = obj.LengthOfLongestSubstring(" ");
            Assert.Equal(1, result);
        }

        [Fact]
        public void case_11()
        {
            var result = obj.LengthOfLongestSubstring("tmmzuxt");
            Assert.Equal(5, result);
        }


    }
}
